### ISSUE TITLE
돈이 업서요

### ISSUE THREAD

**Issue by dn1t** [1-EXON/Discord-Token-Grabber#1]
# _**돈을 주세여 ㅎㅎ**_

돈을 줘야 하는 이유:
- 난 착하다
- 게다가 난 착하다
- 심지어 난 착하다

근거는 충분하니 빨리 돈을 주세요

**Comment by dn1t** [comment]
외 답변이 업서?

**Comment by dn1t** [comment]
싱고하빈다

**Comment by dn1t** [comment]
- # **샌즈__**

**Comment by dn1t** [comment]
- # @1-EXON **_```
샌즈
```_**

**Comment by dn1t** [comment]
_샌즈**ㅎㅎ**_

**Comment by dn1t** [comment]
👍눌르면 색이 입혀진다... 진짜 신기해

**Comment by sihyeokpark** [comment]
???

**Comment by sihyeokpark** [comment]
@thoratica 안녕하세요 고객님의 소중한 의견 잘 간직하겠습니다. 하지만 이 건안은 상당히 또라띠까 하기 때문에 실행이 어려울 듯 합니다. 양해를 구하고 넓은 아량으로 이해해주시기 바랍니다.

**Comment by kiki7000** [comment]
@1-EXON 안녕하세요 키키입니다.
저도 돈이 없습니다
제 의견은 또리띠까하지 않으니 들어주세요

**Comment by dn1t** [comment]
전 또라띠까하지 않고 싸고비레하니 돈이 업서요

**Comment by dn1t** [comment]
> # _**돈을 주세여 ㅎㅎ**_
> 
> 돈을 줘야 하는 이유:
> 
>     * 난 착하다
> 
>     * 게다가 난 착하다
> 
>     * 심지어 난 착하다
> 
> 
> 근거는 충분하니 빨리 돈을 주세요

근거는 충분히 재시햇서여

**Comment by sihyeokpark** [comment]
@kiki7000 안녕하세요 고객님의 소중한 의견 잘 간직하겠습니다. 하지만 이 건안은 상당히 키키 하기 때문에 실행이 어려울 듯 합니다. 양해를 구하고 넓은 아량으로 이해해주시기 바랍니다.

**Comment by sihyeokpark** [comment]
저도 돈이 없어서 ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ

**Comment by kiki7000** [comment]
아닙니다. 제 의견은 또리띠까 하지 않고 키키하지 않고 키키키키키 합니다

**Comment by kiki7000** [comment]
@thoratica @1-EXON 이거 빨리 Close 해주세요
깃허브 맨 위에 떠서 못해먹겠네

**Comment by dn1t** [comment]
킼히님의 요청으로 닫스빈다.

**Comment by kiki7000** [comment]
다시 여세요
돈이 다시 필요하거든요

**Comment by kiki7000** [comment]
@thoratica

**Comment by dlsideacc** [comment]
머야

**Comment by dya-only** [comment]
SANS.
