### ISSUE TITLE
싱고

### ISSUE THREAD

**Issue by muang4089** [1-EXON/Discord-Token-Grabber#2]
토큰이라니 싱고하자 싱고

**Comment by sihyeokpark** [comment]
@milch4089  안녕하세요 고객님의 소중한 의견 잘 간직하겠습니다. 하지만 이 건안은 상당히 밀츠 하기 때문에 실행이 어려울 듯 합니다. 양해를 구하고 넓은 아량으로 이해해주시기 바랍니다.
